### ISSUE TITLE
Ras Pi Pico Micropython

### ISSUE THREAD

**Issue by vanderjt** [WorldFamousElectronics/Raspberry_Pi#2]
I and @akelley want to use this library for the Pico and are developing in Micropython. We have been able to get the sensor to return analog values but are having trouble choosing a good threshold value for a heartbeat. When scaling the threshold value (accounting for the 10bit to 12bit ADC difference) from one of your example programs we wind up with BPM that is significantly higher than expected. Any advice on threshold values or help translating some of the functions in this library would help a lot. Our micropython script is below.
```
import machine
import utime
from machine import Pin, Timer


sensor_BPM = machine.ADC(28)
conversion_factor = 3.3/65535
thresh = 37200
pin = Pin("LED",Pin.OUT)
holdstate = False
beats = 0
timer=Timer(-1) #virtual timer, the ID will be -1

def interuptHandle(timer):
    #global holdstate
    #holdstate = True
    global beats
    print('flag toggle')
    print('interupting, BPM is: ', (beats*10))
    utime.sleep(1)
    beats = 0

timer.init(period=6000, mode=Timer.PERIODIC, callback=interuptHandle)  

while True:
    if holdstate != True:
        reading = sensor_BPM.read_u16()
        if reading > thresh:
            pin.high()
            beats += 1
            utime.sleep_ms(100)
        else:
            pin.low()
        print("Voltage: ", reading)
    utime.sleep_ms(100)
```

**Comment by biomurph** [comment]
@vanderjt 
Hey, thanks for using Pulse Sensor and implementing on RasPi Pico!
I'm not super familiar with the micropython, but I might be able to help.
First, I need to know more.
What's your sample rate?
Are there dependancies that your code relies on that I need to know?
It looks like you have some 100mS 'sleeps' in there. Are those blocking?
Can you visualize the signal? That always helps. Send a pic of your hardware setup.

You said that you are trying to implement our library functions in micropython, but I don't see any use of our library in your example. 
I can't write your code for you, but if you use my code and have specific questions about it, please ask.

**Comment by vanderjt** [comment]
Hello, thanks for getting back to me. I have been able to graph my data collected, pictured below. The updated code is also below. The pico is logging beats along a 20 second period and using this to calculate beats per minute. It samples at 10Hz as it has a 0.1 second delay between samples. The only question I really have at the moment is if you have any advice for setting the threshold value. I saw the value used in your example and adapted that to a 12-bit ADC but had subpar results as it stood. I then bumped it up to a value that looked to be above all of the secondary pulses and still under the peaks. Is there anything else you would recommend looking for when setting this threshold?
Code:
```
import machine
import utime
from machine import Pin, Timer

sensor_BPM = machine.ADC(28)
conversion_factor = 3.3/65535
thresh = 55000
pin = Pin("LED",Pin.OUT)
holdstate = False
beats = 0
timer=Timer(-1) #virtual timer, the ID will be -1
beatArray = [0,0,0]


def interuptHandle(timer):
    global beats
    global beatArray
    print('interupting, BPM is: ', (beats*3))
    utime.sleep(1)
    beats = 0
    beatArray = [0,0,0]

timer.init(period=20000, mode=Timer.PERIODIC, callback=interuptHandle)  

while True:
    beatArray[2] = beatArray[1]
    beatArray[1] = beatArray[0]
    utime.sleep_ms(100)
    reading = sensor_BPM.read_u16()
    if reading <= (sensor_BPM.read_u16() + 100) or reading >= (sensor_BPM.read_u16()-100):
        reading = sensor_BPM.read_u16()
    beatArray[0] = reading
    if reading > thresh and beatArray[1]>beatArray[2] and beatArray[1] < beatArray[0]:
        pin.high()
        beats += 1
    else:
        pin.low()
    print( reading)
```
Visualized Wave Form:

![ADC Value](https://user-images.githubusercontent.com/92750123/181605204-8343ed61-5d8b-4b4b-8118-52c2a1acdf37.png)

**Comment by biomurph** [comment]
Hi @vanderjt 
There are many ways to determine BPM and IBI to understand heart rate and the dynamic of the parasympathetic and sympathetic nervous system.  
For sure, a sample rate of 10Hz is way too slow. Think about it. that means that any BPM value you get is going to be way off the actual. 
What you need to find is the 'moment of heart beat'. That is usually associated with the steepest part of the rising edge of the pulse waveform. No way you will find it relying on 10Hz sample rate.
You may be able to use wavelets to derive the moment of heartbeat, but I don't see you implementing wavelets.

We have the Pico on our sights for integration into our ecology, but it will take some time.

Another thing, the threshold is NOT the way to find the beat. As mentioned, the moment of heart beat is what you need to look for, and it is found within the morphology of the pulse waveform. 
Please do more work, and then we'll talk more.
